apps/products/urls.py
from django.urls import path

from apps.products import views
urlpatterns = [
    path(route='create/', view=views.ProductCreateView.as_view(), name='create'),
    path(route='', view=views.ProductListView.as_view(), name='list'),
    path(route='<slug:slug>/', view=views.ProductDetailView.as_view(), name='detail'),
    path(route='<slug:slug>/add-to-cart', view=views.add_to_cart, name='add-to-cart'),
    path(route='<slug:slug>/ask-question/', view=views.ask_question, name='ask-question'),
    path(route='<slug:slug>/<int:question_id>/answer/', view=views.answer_question, name='answer-question'),
]

d_commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render
from apps.notifications.models import Notification

def home(request):
    context = {}
    if request.user.is_authenticated:
        context['unread_notifications'] = Notification.objects.filter(
            receiver=request.user.profile,
            is_read=False
        ).order_by('-created_at')[:3]
    return render(request, 'home.html', context=context)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('users/', include(('apps.users.urls', 'users'), namespace='users')),
    path('products/', include(('apps.products.urls', 'products'), namespace='products')),
    path('orders/', include(('apps.orders.urls', 'orders'), namespace='orders')),
    path('notifications/', include(('apps.notifications.urls', 'notifications'), namespace='notifications')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/products/models.py
from decimal import Decimal
from django.utils.text import slugify
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

from apps.products.validators import validate_image_size
from apps.users.models import Profile
# Create your models here.
class ProductCategory(models.Model):
    """Model definition for ProductCategory."""

    name = models.CharField(max_length=50)
    description = models.CharField(max_length=50, blank=True)
    class Meta:
        """Meta definition for ProductCategory."""

        verbose_name = 'Product Category'
        verbose_name_plural = 'Product Categories'

    def __str__(self):
        """Unicode representation of ProductCategory."""
        return self.name


class Brand(models.Model):
    """Model definition for Brand."""

    # TODO: Define fields here
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        """Meta definition for Brand."""

        verbose_name = 'Brand'
        verbose_name_plural = 'Brands'
        ordering = ['name']

    def __str__(self):
        """Unicode representation of Brand."""
        return self.name


class Product(models.Model):
    """Model definition for Product."""

    brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    categories = models.ManyToManyField(ProductCategory)
    seller = models.ForeignKey(Profile, on_delete=models.CASCADE)
    sku = models.CharField(max_length=20)
    price = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.01'))]
    )
    description = models.TextField(blank=True)
    stock_qty = models.PositiveIntegerField()
    slug = models.SlugField(unique=True)
    picture = models.ImageField(
        upload_to='product_pics',
        validators=[validate_image_size],
        null=True
    )
    condition = models.CharField(
        choices=[
            ('new', 'New'),
            ('used', 'Used'),
            ('refurbished', 'Refurbished')
        ],
        default='new',
        max_length=15
    )

    @property
    def avg_score(self):
        reviews = self.reviews.all()
        if not reviews:
            return 0
        return round(sum(reviews.values_list('score', flat=True)) / reviews.count(), 1)

    class Meta:
        """Meta definition for Product."""

        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def in_stock(self):
        return self.stock_qty > 0

    def __str__(self):
        """Unicode representation of Product."""
        return self.name

    def get_reviews_by_score(self):
        """Get a dicttionary like this:
        Key: score of the review (from 1 to 5)
        Value: Number of review with this score
        """
        count = self.reviews.all().count()
        if not count:
            return {k: 0 for k in range(1,6)}
        return {k: self.reviews.filter(score=k).count() / count * 100  for k in range(1,6)}

    def get_categories(self):
        return self.categories.all()
    @staticmethod
    def create_slug(seller, product_name):
        product_slug = slugify(product_name).lower()
        return f'{seller.pk}-{product_slug}'

    @staticmethod
    def get_product_set_categories(products):
        categories = set()
        for product in products:
            for category in product.categories.all():
                categories.add(category)
        return categories


class Attribute(models.Model):
    """Model definition for Attribute."""

    name = models.CharField(max_length=50)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='attributes')
    value = models.CharField(max_length=20)

    class Meta:
        """Meta definition for Attribute."""

        verbose_name = 'Attribute'
        verbose_name_plural = 'Attributes'

    def __str__(self):
        """Unicode representation of Attribute."""
        return self.name

class ProductQuestion(models.Model):
    """Model definition for ProductQuestion."""

    # TODO: Define fields here
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='questions'
    )
    questioner = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        related_name='questioner'
    )
    responder = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        related_name='responder'
    )
    question = models.TextField()
    answer = models.TextField(blank=True)
    pub_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        """Meta definition for ProductQuestion."""

        verbose_name = 'Product Question'
        verbose_name_plural = 'Product Questions'
        ordering = ['-pub_date']

class ProductReview(models.Model):
    """Model definition for ProductReview."""

    # TODO: Define fields here
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='reviews'
    )
    reviewer = models.ForeignKey(Profile, on_delete=models.CASCADE)
    score = models.SmallIntegerField(
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1)
        ]
    )
    description = models.TextField(blank=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    order_line = models.OneToOneField(
        'orders.OrderLine',
        on_delete=models.CASCADE,
        null=True
    )

    class Meta:
        """Meta definition for ProductReview."""
        constraints = [
            models.UniqueConstraint(
                fields=['order_line', 'reviewer'],
                name='unique_product_review'
            )
        ]
        verbose_name = 'Product Review'
        verbose_name_plural = 'Product Reviews'
        ordering = ['-pub_date']

apps/products/forms.py
from django import forms
from django.forms.models import inlineformset_factory

from apps.products.models import Product, Attribute, ProductReview
class ProductForm(forms.ModelForm):
    """Form definition for Product."""

    class Meta:
        """Meta definition for Productform."""

        model = Product
        exclude = ('seller', 'slug')
        widgets = {
            'picture': forms.FileInput(attrs={'class': 'form-control'}),
            'brand': forms.Select(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
            'categories': forms.CheckboxSelectMultiple(attrs={'class': 'form-check-input'}),
            'sku': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'stock_qty': forms.NumberInput(attrs={'class': 'form-control'}),
            'condition': forms.RadioSelect()
        }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super(ProductForm, self).__init__(*args, **kwargs)

    def clean_sku(self):
        "sku must be unique per product by the same seller"
        sku = self.cleaned_data['sku']
        seller = self.request.user.profile
        if Product.objects.filter(seller=seller, sku=sku).exists():
            raise forms.ValidationError("You already used this sku")
        return sku

    def save(self):
        data = self.cleaned_data
        categories = data.pop('categories')
        seller = self.request.user.profile
        slug = Product.create_slug(seller, data['name'])
        product = Product.objects.create(seller=seller, slug=slug, **data)
        for category in categories:
            product.categories.add(category)
        product.save()
        return product

class AttributeForm(forms.ModelForm):
    """Form definition for Attribute."""

    class Meta:
        """Meta definition for Attributeform."""

        model = Attribute
        exclude = ('product', )
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control form-control-sm', 'placeholder': 'Name'}),
            'value': forms.TextInput(attrs={'class': 'form-control form-control-sm', 'placeholder': 'Value'})
        }


AttributeFormSet = inlineformset_factory(
    Product,
    Attribute,
    form=AttributeForm,
    min_num=3,
    validate_min=True,
    extra=3,
    can_delete=False
)

class ProductReviewForm(forms.ModelForm):
    """Form definition for ProductReview."""

    class Meta:
        """Meta definition for ProductReviewform."""

        model = ProductReview
        fields = ('score', 'description')
        widgets = {
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 4})
        }

    def __init__(self, *args, **kwargs):
        self.reviewer = kwargs.pop('reviewer')
        self.order_line = kwargs.pop('order_line')
        super(ProductReviewForm, self).__init__(*args, **kwargs)

    def save(self):
        data = self.cleaned_data
        review = ProductReview(
            reviewer=self.reviewer,
            product=self.order_line.product,
            order_line=self.order_line,
            **data
        )
        review.save()
        return review

apps/products/views.py
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.db.models import Q

from apps.products.models import Product,ProductQuestion, Brand, ProductReview
from apps.products.forms import ProductForm, AttributeFormSet, ProductReviewForm
from apps.orders.models import OrderLine
from apps.notifications.models import Notification
from apps.notifications.mixins import NotificationMixin
# Create your views here.
class ProductListView(NotificationMixin, ListView):
    """ List view for Product model"""
    model = Product
    template_name = "products/list.html"
    context_object_name = 'products'

    def get_queryset(self):
        keyword = self.request.GET.get('search', '')
        category = self.request.GET.get('category')
        condition =self.request.GET.get('condition')
        queryset = Product.objects.exclude(stock_qty=0)
        if self.request.user.is_authenticated:
            queryset = queryset.exclude(seller=self.request.user.profile)
        if keyword:
            queryset = queryset.filter(
                Q(name__icontains=keyword)
                | Q(brand__name__icontains=keyword)
            )
        if category:
            queryset = queryset.filter(categories__name=category)
        if condition:
            queryset = queryset.filter(condition=condition)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_val'] = self.request.GET.get('search', '')
        context['categories'] = Product.get_product_set_categories(
            context.get('products')
        )
        return context


class ProductDetailView(NotificationMixin, DetailView):
    """ Detail view for Product Model"""
    model = Product
    template_name = "products/detail.html"
    context_object_name = 'product'

    def get_queryset(self):
        queryset = Product.objects.exclude(stock_qty=0)
        if self.request.user.is_authenticated:
            queryset = queryset.exclude(seller=self.request.user.profile)
        return queryset


class ProductCreateView(LoginRequiredMixin, NotificationMixin, CreateView):
    """ Create view for Product model"""
    model = Product
    template_name = "products/create.html"
    form_class = ProductForm
    formset_class = AttributeFormSet
    success_url = reverse_lazy('users:my-profile')

    def get_form_kwargs(self):
        kwargs = super(ProductCreateView, self).get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(ProductCreateView, self).get_context_data(**kwargs)
        context['brands'] = Brand.objects.all()
        if self.request.POST:
            context['formset'] = AttributeFormSet(self.request.POST)
        else:
            context['formset'] = AttributeFormSet()
        return context

    def form_valid(self, form):
        self.object = form.save()
        formset = AttributeFormSet(self.request.POST)
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
            return HttpResponseRedirect(self.get_success_url())
        return self.form_invalid(form)

@login_required
def ask_question(request, slug):
    if request.method == 'POST':
        if request.POST.get('question'):
            product = Product.objects.get(slug=slug)
            question_vals = {
                'question': request.POST.get('question'),
                'product': Product.objects.get(slug=slug),
                'questioner': request.user.profile,
                'responder': product.seller
            }
            question = ProductQuestion.objects.create(**question_vals)
            Notification.send_notification(
                sender=request.user.profile,
                receiver=product.seller,
                title=f'New question on product: {product}',
                message=f'Question: "{question.question}"',
                url=reverse_lazy('users:questions')
            )
    return redirect('products:detail', slug=slug)

@login_required
def answer_question(request, slug, question_id):
    if request.method == 'POST':
        if request.POST.get('answer'):
            product = Product.objects.get(slug=slug)
            question = ProductQuestion.objects.get(
                pk=question_id,
                product=product,
            )
            if question:
                question.answer = request.POST.get('answer')
                question.save()
                Notification.send_notification(
                sender=request.user.profile,
                receiver=question.questioner,
                title=f'New answer on product: {product}',
                message=f'Answer: "{question.answer}"',
                url=reverse_lazy('products:detail', kwargs={'slug': product.slug})
            )
    return redirect('users:questions')

@login_required
def add_to_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    cart = request.user.profile.shopping_cart
    cart.add_item(product)
    return redirect('users:cart:cart')

class ProductReviewCreateView(LoginRequiredMixin, NotificationMixin, CreateView):
    model = ProductReview
    template_name = "products/reviews/add.html"
    form_class = ProductReviewForm
    success_url = reverse_lazy('users:my-profile')

    def get_context_data(self, **kwargs):
        context = super(ProductReviewCreateView, self).get_context_data(**kwargs)
        context['order_line'] = get_object_or_404(
            OrderLine,
            pk=self.kwargs['pk']
        )
        return context

    def get_form_kwargs(self):
        kwargs =  super().get_form_kwargs()
        kwargs['order_line'] = get_object_or_404(
            OrderLine,
            pk=self.kwargs['pk']
        )
        kwargs['reviewer'] = self.request.user.profile
        return kwargs

templates/products/create.html
{% extends 'base.html' %}

{% block head_content %}
    <title>Publish Product</title>
{% endblock head_content %}


{% block container %}

    <div class="container w-75">
        <h1>Publish Product</h1>
    </div>
    <div class="container w-75 border rounded">
        {% if form.errors %}
            <p>There were errors in the form:</p>
            <ul>
                {% for field in form %}
                    {% for error in field.errors %}

                        <li>{{field.name}}: {{ error }}</li>
                    {% endfor %}
                {% endfor %}
            </ul>
        {% endif %}
        <form method="post" action="{% url 'products:create' %}" enctype="multipart/form-data">
            {% csrf_token %}

            {# name, brand and picture#}
            <div class="mt-3">
                <div class="row mb-3">
                    <div class="col-6">
                        {{form.name.label_tag}}
                        {{form.name}}
                    </div>
                    <div class="col-6">
                        {{form.brand.label_tag}}
                        {{form.brand}}
                    </div>
                    <div class="col-12 mt-3">
                        {{form.picture.label_tag}}
                        {{form.picture}}
                    </div>
                    <div class="col-12 mt-3">
                        {{form.condition.label_tag}}
                        {% for radio in form.condition %}
                            <div class="form-check form-check-inline">
                                {{radio}}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>

            {# description #}
            <div class="mt-3">
                {{form.description.label_tag}}
                {{form.description}}
            </div>

            {# categories #}
            <div class="mt-3">
                {{form.categories.label_tag}}
                <div class="row row-cols-5 mt-2">
                    {% for category in form.categories %}
                    <div class="col">
                        {{category}}
                    </div>
                    {% endfor %}
                </div>
            </div>

            {# price, sku and stock quantity #}
            <div class="mt-3">
                <div class="row">
                    <div class="col-md">
                        {{form.price.label_tag}}
                        <div class="input-group">
                            <div class="input-group-text">$</div>
                            {{form.price}}

                        </div>
                    </div>
                    <div class="col-md">
                        {{form.stock_qty.label_tag}}
                        {{form.stock_qty}}
                    </div>
                    <div class="col-md">
                        {{form.sku.label_tag}}
                        {{form.sku}}
                    </div>
                </div>
            </div>

            {# attributes #}
            <div class="mt-3">
                {% if formset.errors %}
                <p>There were errors in the formset:</p>
                <ul>
                    {% for error in formset.non_form_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}

                <h4>Attributes</h4>
                {{ formset.management_form }}
                <div class="row">
                    {% for form in formset %}
                    <div class="col-6 mb-3">
                        {% for field in form %}
                            {{field}}
                            {{field.errors}}
                        {% endfor %}
                    </div>
                    {% endfor %}
                </div>
            </div>

            <hr class="my-4">
            <input class="btn btn-primary w-100 mb-3" type="submit" value="Save">
        </form>
    </div>
{% endblock %}

templates/products/detail.html
{% extends 'base.html' %}

{% block head_content %}
    <title>{{product.name}}</title>
{% endblock head_content %}


{% block container %}
    <div class="container">
        <div class="row">
            <div class="col-6 justiy-content-center ">
                <img class="d-block mx-auto" height="350" width="350" src="{{product.picture.url}}">
            </div>
            <div class="col-6">
                <div class="row">
                    <div class="col">
                        <div class="container mt-2">
                            <p class="text-muted">{{product.get_condition_display}}</p>
                            <h5>{{product.brand}}</h5>
                            <h5 class="card-title">{{product.name}}</h5>
                            <h4 class="card-title">$ {{product.price}}</h4>
                            <br>
                            <ul>
                                {% for attribute in product.attribute_set.all %}
                                <li class="text-muted">{{attribute.name}}: {{attribute.value}}</li>
                                {% endfor %}
                            </ul>
                            <br>
                            {% if product.reviews %}
                            <div>{% include 'products/stars.html' %}</div>
                            {% endif %}

                        </div>
                    </div>
                    <div class="col">
                        <div class="card">
                            <div class="card-body">
                                <h6>Seller: {{product.seller.user.username}}</h6>
                                <p>Stock Quantity: {{product.stock_qty}}</p>
                                <br>
                                <a class="btn btn-primary w-100" href="{% url 'products:add-to-cart' product.slug %}">Add to cart</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <hr>

        {# Product Description #}
        <div class="card" style="background-color: rgb(248, 248, 248);">
            <div class="card-body">
                <h3 class="card-title">Description</h3>
                {{ product.description | linebreaks }}
            </div>
        </div>
        <hr>

        <div class="card" style="background-color: rgb(248, 248, 248);">
            <div class="card-body">
                <h3 class="card-title">Attributes</h3>
                <table class="table table-bordered">
                    <tbody>
                        {% for attr in product.attributes.all %}
                            <tr>
                                <td><strong>{{attr.name}}</strong></td>
                                <td>{{attr.value}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
        <hr>


        {# Questions #}
        <div class="card" style="background-color: rgb(248, 248, 248);">
            <div class="card-body">
                <h3 class="card-title">Questions</h3>
                {% for question in product.questions.all %}
                    <ul>
                        {% if question.answer %}
                            <li>{{question.question}}</li>
                            <li class="text-muted">{{question.answer}}</li>
                        {% else %}
                            <li>{{question.question}} <p class="text-muted">unanswered question</p></li>

                            {% if request.user.profile == product.seller %}
                                <form action="{% url 'products:answer-question' product.slug question.pk%}" method="post">
                                    {% csrf_token %}
                                    <input class="form-control" type="text" name="answer" placeholder="Answer question..." required>
                                </form>
                            {% endif %}
                        {% endif %}
                    </ul>
                {% empty %}
                    <p class="text-muted">There are no questions yet</p>
                {% endfor %}
                <br>
                {% if request.user.profile != product.seller %}
                <form action="{% url 'products:ask-question' product.slug %}" method="post">
                    {% csrf_token %}
                    <input name="question" class="form-control" type="text" placeholder="Ask a question..." required>
                </form>
                {% endif %}

            </div>
        </div>
        <hr>

        {# Reviews #}
        <div class="card" style="background-color: rgb(248, 248, 248);">
            <div class="card-body">
                <h2 class="card-title">Reviews</h2>
                <hr>
                <div class="row">

                    <div class="col-2">
                        <h4>Score: <strong>{{product.avg_score}} / 5</strong></h4>
                        {% for rating, count in product.get_reviews_by_score.items %}
                        <div class="row align-items-center">
                            <div class="col-10 align-items-center">
                                <div class="progress"
                                    role="progressbar"
                                    aria-label="Basic example"
                                    aria-valuenow="{{count}}"
                                    aria-valuemin="0"
                                    aria-valuemax="{{product.reviews.all.count}}"
                                    style="height: 2px">
                                        <div class="progress-bar" style="width: {{count}}%;"></div>
                                </div>
                            </div>
                            <div class="col-1">
                                {{rating}}
                            </div>
                        </div>
                        {% endfor %}
                    </div>

                    <div class="col-10">
                        {% for review in product.reviews.all %}
                            <h5 class="card-subtitle mt-1 mb-1">{{review.score}}/5</h5>
                            <p class="card-text">{{review.description}}</p>
                        {% empty %}
                            <p class="text-muted">There are no reviews yet</p>
                        {% endfor %}
                    </div>

                </div>
            </div>
        </div>
        <br>
    </div>
{% endblock container %}

templates/products/list.html
{% extends 'base.html' %}
{% load static %}

{% block head_content %}
    <title>D - Commerce</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/stars.css' %}"/>
{% endblock head_content %}


{% block container %}
    <div class="container">
        <div class="row">
            {% if products %}
            <div class="col-2 justify-content center rounded" style="background-color: rgb(248, 248, 248);">
                <div class="card mt-2">
                    <div class="card-body">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Categories</li>
                            {% for category in categories %}
                            <a  class="list-group-item"
                                href="{% url 'products:list' %}?search={{search_val | urlencode}}&category={{category | urlencode}}">
                                {{category}}
                            </a>
                            {% endfor %}
                        </ul>
                        <br>
                        <ul class="list-group list-group-flush">
                            <a  class="list-group-item"
                                href="{% url 'products:list' %}?search={{search_val | urlencode}}&category={{category | urlencode}}&condition=new">
                                New
                            </a>
                            <a  class="list-group-item"
                                href="{% url 'products:list' %}?search={{search_val | urlencode}}&category={{category | urlencode}}&condition=used">
                                Used
                            </a>
                            <a  class="list-group-item"
                                href="{% url 'products:list' %}?search={{search_val | urlencode}}&category={{category | urlencode}}&condition=refurbished">
                                Refurbished
                            </a>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-10">
                {% for product in products %}
                <div class="card mb-2">
                    <div class="card-body">
                        <div class="d-flex">
                            <div class="flex-shrink-0">
                                <img class="img-fluid" width="160" height="160" src="{{product.picture.url}}">
                            </div>
                            <div class="d-flex flex-column ms-5">
                                <div class="p-1"><p>{{product.name}}</p></div>
                                <div class="p-1"><h4 class="card-text">$ {{product.price}}</h4></div>
                                <a href="{% url 'products:detail' product.slug %}" class="stretched-link"></a>
                                <div class="p-1">
                                    {% include 'products/stars.html' %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% else %}
            <div class="card mb-2">
                <div class="card-body">
                    <h2 class="card-title">There are no products than match your search</h2>
                    <p class="card-text">Maybe you can try with another search</p>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
{% endblock container %}