apps/notifications/urls.py
from django.urls import path

from apps.notifications import views
urlpatterns = [
    path('<int:pk>/', view=views.mark_as_read, name='as_read')
]

apps/users/urls.py
from django.urls import path, include

from apps.users import views

cart_urls = [
    path('', views.ShoppingCartView.as_view(), name='cart'),
    path('<int:pk>/change_qty', views.change_product_qty, name='change-qty'),
    path('<int:pk>/remove', views.remove_item, name='remove_item'),
]

adressess_urls = [
    path('', views.ProfileAddressListView.as_view(), name='list'),
    path('create/', views.ProfileAddressCreateView.as_view(), name='create'),
    path('<int:pk>/', views.ProfileAddressUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete', views.delete_profile_address, name='delete'),
]

paymentcards_urls = [
    path('', views.ProfilePaymentListView.as_view(), name='list'),
    path('create/', views.ProfilePaymentCreateView.as_view(), name='create'),
    path('<int:pk>/', views.ProfilePaymentUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete', views.delete_profile_payment, name='delete'),
]

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(),name='signup'),

    path('my-profile/', views.ProfileDetailView.as_view(), name='my-profile'),
    path('my-profile/change_password', views.ProfileChangePasswordView.as_view(), name='change-password'),
    path('my-profile/questions/', views.ProductQuestionListView.as_view(), name='questions'),
    path('my-profile/published-products/', views.PublishedProductsListView.as_view(), name='published-products'),
    path('my_profile/published-products/<int:pk>/update_qty/', views.update_stock_qty, name='update_qty'),

    path('my-profile/cart/',include((cart_urls, 'cart'))),
    path('my-profile/addresses/',include((adressess_urls, 'address'))),
    path('my-profile/payment-cards/',include((paymentcards_urls, 'paymentcard'))),
]

d_commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render
from apps.notifications.models import Notification

def home(request):
    context = {}
    if request.user.is_authenticated:
        context['unread_notifications'] = Notification.objects.filter(
            receiver=request.user.profile,
            is_read=False
        ).order_by('-created_at')[:3]
    return render(request, 'home.html', context=context)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('users/', include(('apps.users.urls', 'users'), namespace='users')),
    path('products/', include(('apps.products.urls', 'products'), namespace='products')),
    path('orders/', include(('apps.orders.urls', 'orders'), namespace='orders')),
    path('notifications/', include(('apps.notifications.urls', 'notifications'), namespace='notifications')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

</head>
<body>

    {% include 'nav.html' %}
    <div class="container mt-5 mb-5">
        {% block container %}{% endblock%}
    </div>
    {% include 'footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

templates/footer.html
<footer class="container">
    <hr>
    <div class="container">
        <p class="text-muted fw-light">D - COMMERCE</p>
        <p class="text-muted fw-light">
            Disclaimer: This Django marketplace project is a prototype and has no real-world functionality. The purpose of this project is to showcase the design and functionality of a potential marketplace. Any products or services listed on this project are for demonstration purposes only and cannot be purchased or sold. Please do not enter any personal information or payment details into the project. We do not collect or store any user data. By using this project, you acknowledge that it is not a real marketplace and any transactions or interactions are for testing purposes only. This project is provided as-is and without warranty. We are not responsible for any damages or losses incurred through the use of this project.
        </p>
        <ul class="list-inline">
            <li class="list-inline-item">Project by Uriel Mayo</li>
            <li class="list-inline-item">
                <a href="https://github.com/urielmayo">
                    <i class="bi bi-github"></i>
                </a>
            </li>
            <li class="list-inline-item">
                <a href="https://www.linkedin.com/in/uriel-mayo/">
                    <i class="bi bi-linkedin"></i>
                </a>
            </li>
        </ul>
    </div>
</footer>

templates/home.html
{% extends 'base.html' %}


{% block head_content %}
    <title>D - Commerce</title>
{% endblock head_content %}


{% block container %}
    <div class="container-fluid w-75 rounded align-items-center" style="background-color: #eee;">
        <h1 class="text-center">D - COMMERCE</h1>
        <p class="text-center fw-light">Buy and Sell products online.</p>
        <br>
        <div class="container">
            <pre class="text-muted">
                This is an e-commerce simulator using Django, Postgres & Bootstrap mainly.
                Its main capabilities are:
                    - Register, login and logout users
                    - Publish products and manage stock quantity
                    - Answer questions and review products
            </pre>
        </div>
    </div>
{% endblock container %}

templates/nav.html
<nav class="navbar navbar-expand-lg" style="background-color: #0C4B33;">
    <div class="container-fluid">

        <a class="navbar-brand text-white me-5" href="{% url 'home' %}">D - COMMERCE</a>

        <form class="d-flex flex-grow-1 me-5" role="search" action="{% url 'products:list' %}">
            <div class="input-group">
                <input class="form-control" name="search" value="{{search_val}}" type="search" placeholder="Search" aria-label="Search" required>
                <button class="btn btn-light" type="submit"><i class="bi bi-search"></i></button>
            </div>
        </form>

        <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'users:cart:cart' %}" class="nav-link text-white"><i class="bi bi-cart-fill"></i> Cart</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="bi bi-bell-fill"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end">

                        {% for notification in unread_notifications %}
                        <li><a class="dropdown-item" href="{% url 'notifications:as_read' notification.pk%}">{{notification.title}}</a></li>
                        {% empty%}
                        <li>
                            <div class="container text-muted">There are no unread notifications</div>
                        </li>
                        {% endfor %}
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'users:my-profile' %}">Check all notifications</a></li>

                    </ul>
                </li>
            {% endif %}

            <li>
                {% if request.user.is_anonymous %}
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'users:login' %}">Login</a>
                </li>
                {% else %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{request.user.username}}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item" href="{% url 'users:my-profile'%}">Profile</a></li>
                        <li><a class="dropdown-item" href="{% url 'products:create' %}">Publish Product</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'users:logout' %}">Log out</a></li>
                    </ul>
                </li>
                {% endif %}
            </li>

        </ul>
    </div>
</nav>