apps/orders/urls.py
from django.urls import path

from apps.orders import views
from apps.products.views import ProductReviewCreateView
urlpatterns = [
    path('', view=views.OrderListView.as_view(), name='list'),
    path('create/', view=views.OrderCreateView.as_view(), name='create'),

    path('sales/', view=views.OrderLinesListView.as_view(), name='sales-list'),
    path('sales/<int:pk>/ship/', view=views.ship_product, name='ship-product'),
    path('sales/<int:pk>/deliver/', view=views.deliver_product, name='deliver-product'),
    path('order_lines/<int:pk>/cancel/', view=views.cancel_order_line, name='cancel_order_line'),
    path('order_lines/<int:pk>/add-review/', view=ProductReviewCreateView.as_view(), name='add-review')

]

d_commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render
from apps.notifications.models import Notification

def home(request):
    context = {}
    if request.user.is_authenticated:
        context['unread_notifications'] = Notification.objects.filter(
            receiver=request.user.profile,
            is_read=False
        ).order_by('-created_at')[:3]
    return render(request, 'home.html', context=context)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('users/', include(('apps.users.urls', 'users'), namespace='users')),
    path('products/', include(('apps.products.urls', 'products'), namespace='products')),
    path('orders/', include(('apps.orders.urls', 'orders'), namespace='orders')),
    path('notifications/', include(('apps.notifications.urls', 'notifications'), namespace='notifications')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/orders/models.py
from django.db import models

from apps.users.models import Profile, ProfileAddress, ProfilePayment
from apps.products.models import Product

# Create your models here.
class Order(models.Model):
    """Model definition for Order."""

    customer = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
    )
    customer_billing_address = models.ForeignKey(
        ProfileAddress,
        related_name='billing_address',
        on_delete=models.DO_NOTHING,
        limit_choices_to={'type': 'billing'}
    )
    customer_shipping_address = models.ForeignKey(
        ProfileAddress,
        related_name='shipping_address',
        on_delete=models.DO_NOTHING,
        limit_choices_to={'type': 'shipping'}
    )
    customer_payment = models.ForeignKey(
        ProfilePayment,
        on_delete=models.CASCADE,
    )
    subtotal = models.FloatField()
    total_taxes = models.FloatField(blank=True, null=True)
    total = models.FloatField()
    status = models.CharField(
        choices=[
            ('draft', 'Draft'),
            ('paid', 'Paid'),
            ('on_ship', 'On Ship'),
            ('shipped', 'Shipped'),
            ('cancelled', 'Cancelled')
        ],
        default='draft',
        max_length=10
    )
    create_date = models.DateTimeField(auto_now_add=True)
    note = models.TextField(blank=True)

    class Meta:
        """Meta definition for Order."""

        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

    def __str__(self):
        """Unicode representation of Order."""
        return f'Order #{self.pk}'

class OrderLine(models.Model):
    """Model definition for OrderLine."""

    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order_lines')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.SmallIntegerField()
    discount = models.FloatField(blank=True, null=True)
    unit_price = models.FloatField()
    line_total = models.FloatField()
    status = models.CharField(
        choices=[
            ('to_ship', 'To Ship'),
            ('in_transit', 'In Transit'),
            ('delivered', 'Delivered'),
            ('cancelled', 'Cancelled')
        ],
        default='to_ship',
        max_length=30
    )

    class Meta:
        """Meta definition for OrderLine."""

        verbose_name = 'Order Line'
        verbose_name_plural = 'Order Lines'

    def get_status_color(self):
        status_color = {
            'to_ship': 'text-muted',
            'in_transit': 'text-warning',
            'delivered': 'text-success',
            'cancelled': 'text-danger'
        }
        return status_color[self.status]

apps/orders/forms.py
from django import forms

from apps.orders.models import Order, OrderLine
from apps.users.models import ProfileAddress, ProfilePayment
class OrderForm(forms.ModelForm):
    """Form definition for Order."""

    class Meta:
        """Meta definition for Orderform."""

        model = Order
        fields = (
            'customer_shipping_address',
            'customer_payment'
        )
        widgets = {
            'customer_shipping_address': forms.RadioSelect(),
            'customer_payment': forms.RadioSelect(),
        }

    def __init__(self, *args, **kwargs):
        self.profile = kwargs.pop('profile')
        super(OrderForm, self).__init__(*args, **kwargs)
        self.fields['customer_shipping_address'].queryset = self.profile.addresses.filter(
            type='shipping'
        )
        self.fields['customer_payment'].queryset = self.profile.payment_cards

    def save(self):
        data = self.cleaned_data
        profile = self.profile
        cart = self.profile.shopping_cart

        data.update({
            'customer': profile,
            'customer_billing_address': data['customer_shipping_address'],
            'status': 'paid',
            'subtotal': cart.total,
            'total': cart.total
        })
        order = Order(**data)
        order.save()

        for line in cart.get_lines_vals():
            OrderLine.objects.create(order=order, **line)

        for line in cart.shopping_cart_lines.all():
            line.product.stock_qty -= line.quantity
            line.product.save()
        cart.empty()

        return order

apps/orders/views.py
from django.views.generic import CreateView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect
from django.contrib.messages.views import SuccessMessageMixin

from apps.orders.models import Order, OrderLine
from apps.orders.forms import OrderForm
from apps.orders.mixins import CartNotEmptyMixin
from apps.notifications.models import Notification
from apps.notifications.mixins import NotificationMixin
# Create your views here.

class OrderCreateView(CartNotEmptyMixin, NotificationMixin, SuccessMessageMixin, CreateView):
    model = Order
    template_name = "orders/create.html"
    form_class = OrderForm
    success_url = reverse_lazy('orders:list')
    success_message = "Order created succesfully!"

    def get_context_data(self, **kwargs):
        context = super(OrderCreateView, self).get_context_data(**kwargs)
        context['cart'] = self.request.user.profile.shopping_cart
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['profile'] = self.request.user.profile
        return kwargs

    def form_valid(self, form):
        response = super().form_valid(form)
        Notification.send_notification(
            sender=None,
            receiver=self.request.user.profile,
            title=f'Order creted: #{self.object.pk}',
            message='Congratulations! You have just  bought this item',
            url=reverse_lazy('orders:list')
        )
        return response

class OrderListView(LoginRequiredMixin, NotificationMixin, ListView):
    model = Order
    template_name = "orders/list.html"
    context_object_name = 'orders'

    def get_queryset(self):
        return Order.objects.filter(customer=self.request.user.profile).order_by('-create_date')

class OrderDetailView(LoginRequiredMixin, NotificationMixin, DetailView):
    model = Order
    template_name = "orders/detail.html"
    context_object_name = 'order'

class OrderLinesListView(LoginRequiredMixin, NotificationMixin, ListView):
    model = OrderLine
    template_name = "orders/sold_products.html"
    context_object_name = 'sold_products'

    def get_queryset(self):
        return OrderLine.objects.filter(
            product__seller=self.request.user.profile
        )

@login_required
def ship_product(request, pk):
    line = get_object_or_404(
        OrderLine,
        pk=pk,
        product__seller=request.user.profile
    )
    line.status = 'in_transit'
    line.save()
    Notification.send_notification(
        sender=request.user.profile,
        receiver=line.order.customer,
        title='Your product has been shipped',
        message=f'Your {line.product.name} has been shipped. It will arrive in a few days',
        url=reverse_lazy('orders:list')
    )
    return redirect('orders:sales-list')

@login_required
def deliver_product(request, pk):
    line = get_object_or_404(
        OrderLine,
        pk=pk,
        product__seller=request.user.profile
    )
    line.status = 'delivered'
    line.save()
    Notification.send_notification(
        sender=request.user.profile,
        receiver=line.order.customer,
        title='Your product has been delivered',
        message=f'Your {line.product.name} has been delivered.\n'
        'If you enjoy it, please leave a review',
        url=reverse_lazy('orders:list')
    )
    return redirect('orders:sales-list')

@login_required
def cancel_order_line(request, pk):
    order_line = get_object_or_404(
        OrderLine,
        pk=pk,
        status='to_ship',
        order__customer=request.user.profile
    )
    order_line.status = 'cancelled'
    order_line.save()
    return redirect('orders:list')

templates/orders/create.html
{% extends 'base.html' %}


{% block head_content %}
    <title>Checkout</title>
{% endblock head_content %}


{% block container %}
    <div class="row">
        <div class="col-6 border-right">
            {% include 'orders/form.html' %}
        </div>
        <div class="col-5">
            <h3 class="mb-3">Summary</h3>
            <ul class="list-group">
                {% for line in cart.shopping_cart_lines.all %}
                    <li class="list-group-item d-flex justify-content-between">
                        <div>
                            <h6>{{line.product}}</h6>
                            <small>Quantity: {{line.quantity}}</small>
                        </div>
                        <span>{{line.line_total}}</span>
                    </li>
                {% endfor %}
                    <li class="list-group-item d-flex justify-content-between">
                        <span>Total</span>
                        <strong>{{cart.total}}</strong>
                    </li>
            </ul>
        </div>
    </div>
{% endblock container %}

templates/orders/detail.html
{% extends 'base.html' %}

{% block head_content %}
    <title>Order #{{order.pk}}</title>
{% endblock head_content %}


{% block container %}
    <div>
        Agregar Info detallada
    </div>
{% endblock container %}

templates/orders/form.html
<form method="post" action="{% url 'orders:create' %}">{% csrf_token %}
    <div class="row align-items-center gx-2">
        <div class="col-auto">
            <h3>Shipping Address</h3>
        </div>
        <div class="col-1">
            <a class="btn btn-sm btn-outline-primary rounded-pill" href="{% url 'users:address:create' %}?from_order=true">
                <i class="bi bi-plus-lg"></i>
            </a>
        </div>
    </div>
    {{ form.customer_shipping_address }}

    <div class="row align-items-center gx-2 mt-3">
        <div class="col-auto">
            <h3>Payment Card</h3>
        </div>
        <div class="col-1">
            <a class="btn btn-sm btn-outline-primary rounded-pill" href="{% url 'users:paymentcard:create' %}?from_order=true">
                <i class="bi bi-plus-lg"></i>
            </a>
        </div>
    </div>
    {{form.customer_payment}}
    <br>
    <button class="btn w-100 btn-primary " type="submit">Confirm Order</button>
</form>

templates/orders/list.html
{% extends 'base.html' %}

{% block head_content %}
    <title>My Orders</title>
{% endblock head_content %}


{% block container %}
<div class="container w-100">


    {% for msg in messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>{{msg}}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}

    <div class="d-flex align-items-center mb-3">
        <h2 class="me-2">My Orders</h2>
        <div class="vr me-2"></div>
        <h4 class="text-muted">{{orders.count}}</h4>
    </div>
    {% for order in orders %}
    <div class="card mb-5">
        <div class="card-header">
            <div class="d-flex justify-content-between gy-1">
                <div class="p-1">{{order.create_date|date:"SHORT_DATE_FORMAT"}}</div>
                <div class="p-1">Order #{{order.pk}} | Status: {{order.status.capitalize}}</div>
            </div>
        </div>
        <div class="card-body">
            <div class="row align-items-center">
                <div class="col-8">
                    <h5 class="ms-3 mb-3">Items</h5>
                    <ul class="list-group list-group-flush">
                        {% for line in order.order_lines.all %}
                            <div class="list-group-item d-flex">
                                <div class="d-flex-shrink-0">
                                    <img src="{{line.product.picture.url}}" width="60" height="60">
                                </div>
                                <div class="d-flex flex-column ms-3">
                                    <div class="p-0"><h5>{{line.product.name}}</h5></div>
                                    <div class="p-0 text-muted">Quantity: {{line.quantity}}</div>
                                </div>
                                <div class="d-flex flex-column ms-auto align-items-center">
                                    <div class="p-0">
                                        <strong class="text-primary">{{line.product.seller}}</strong>
                                    </div>
                                    <div class="p-0 {{line.get_status_color}} mb-1">
                                        <strong>{{line.get_status_display.upper}}</strong>
                                    </div>

                                    {% if line.status == 'to_ship' %}
                                        <div class="p-0">
                                            <a class="text-danger" href="{% url 'orders:cancel_order_line' line.pk %}">Cancel Order</a>
                                        </div>
                                    {% endif %}

                                    {% if line.status == 'delivered' %}

                                        <div class="p-0">
                                        {% if line.productreview %}
                                            <p>Rating: {{line.productreview.score}}/5</p>
                                        {% else %}
                                            <a href="{% url 'orders:add-review' line.pk %}" class="btn btn-light btn-sm">Leave Review</a>
                                        {% endif %}

                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                    </ul>
                </div>
                <div class="col-4 ">
                    <h5>Details</h5>
                    <div class="d-flex justify-content-between mt-1">
                        <div class="p-0">Total:</div>
                        <div class="p-0">${{order.total}}</div>
                    </div>
                    <hr class="my-1">
                    <div class="d-flex justify-content-between mt-1">
                        <div class="p-0">Send to:</div>
                        <div class="p-0">{{order.customer_shipping_address}}</div>
                    </div>
                    <hr class="my-1">
                    <div class="d-flex justify-content-between">
                        <div class="p-0">Payment:</div>
                        <div class="p-0">{{order.customer_payment.card_provider}} {{order.customer_payment.get_last_digits}}</div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    {% empty %}
    <div class="d-flex mb-4 mt-4">
        There are no orders. Start Shopping!
    </div>
    {% endfor %}
</div>
{% endblock container %}

templates/orders/sold_products.html
{% extends 'base.html' %}


{% block head_content %}
    <title>My Sales</title>
{% endblock head_content %}


{% block container %}
    <div class="container">
        <h2>Sales</h2>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Order #</th>
                    <th scope="col">Product</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Status</th>
                    <th scope="col"><i class="bi bi-three-dots-vertical"></i></th>
                </tr>
            </thead>
            <tbody>
                {% for sale in sold_products %}
                <tr>
                    <th scope="row">{{sale.order.pk}}</th>
                    <td>{{sale.product}}</td>
                    <td>{{sale.quantity}}</td>
                    <td>{{sale.get_status_display}}</td>

                    {% if sale.status == 'to_ship' %}
                    <td><a href="{% url 'orders:ship-product' sale.pk%}">Ship Product</a></td>
                    {% elif sale.status == 'in_transit' %}
                    <td><a href="{% url 'orders:deliver-product' sale.pk%}">Deliver Product</a></td>
                    {% endif %}

                </tr>
                {% empty %}
                <tr>
                    <td colspan="5"> There are no sales yet.</td>
                </tr>
                {% endfor %}

            </tbody>
        </table>
    </div>
{% endblock container %}