apps/notifications/urls.py
from django.urls import path

from apps.notifications import views
urlpatterns = [
    path('<int:pk>/', view=views.mark_as_read, name='as_read')
]

apps/orders/urls.py
from django.urls import path

from apps.orders import views
from apps.products.views import ProductReviewCreateView
urlpatterns = [
    path('', view=views.OrderListView.as_view(), name='list'),
    path('create/', view=views.OrderCreateView.as_view(), name='create'),

    path('sales/', view=views.OrderLinesListView.as_view(), name='sales-list'),
    path('sales/<int:pk>/ship/', view=views.ship_product, name='ship-product'),
    path('sales/<int:pk>/deliver/', view=views.deliver_product, name='deliver-product'),
    path('order_lines/<int:pk>/cancel/', view=views.cancel_order_line, name='cancel_order_line'),
    path('order_lines/<int:pk>/add-review/', view=ProductReviewCreateView.as_view(), name='add-review')

]

apps/users/urls.py
from django.urls import path, include

from apps.users import views

cart_urls = [
    path('', views.ShoppingCartView.as_view(), name='cart'),
    path('<int:pk>/change_qty', views.change_product_qty, name='change-qty'),
    path('<int:pk>/remove', views.remove_item, name='remove_item'),
]

adressess_urls = [
    path('', views.ProfileAddressListView.as_view(), name='list'),
    path('create/', views.ProfileAddressCreateView.as_view(), name='create'),
    path('<int:pk>/', views.ProfileAddressUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete', views.delete_profile_address, name='delete'),
]

paymentcards_urls = [
    path('', views.ProfilePaymentListView.as_view(), name='list'),
    path('create/', views.ProfilePaymentCreateView.as_view(), name='create'),
    path('<int:pk>/', views.ProfilePaymentUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete', views.delete_profile_payment, name='delete'),
]

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(),name='signup'),

    path('my-profile/', views.ProfileDetailView.as_view(), name='my-profile'),
    path('my-profile/change_password', views.ProfileChangePasswordView.as_view(), name='change-password'),
    path('my-profile/questions/', views.ProductQuestionListView.as_view(), name='questions'),
    path('my-profile/published-products/', views.PublishedProductsListView.as_view(), name='published-products'),
    path('my_profile/published-products/<int:pk>/update_qty/', views.update_stock_qty, name='update_qty'),

    path('my-profile/cart/',include((cart_urls, 'cart'))),
    path('my-profile/addresses/',include((adressess_urls, 'address'))),
    path('my-profile/payment-cards/',include((paymentcards_urls, 'paymentcard'))),
]

d_commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render
from apps.notifications.models import Notification

def home(request):
    context = {}
    if request.user.is_authenticated:
        context['unread_notifications'] = Notification.objects.filter(
            receiver=request.user.profile,
            is_read=False
        ).order_by('-created_at')[:3]
    return render(request, 'home.html', context=context)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('users/', include(('apps.users.urls', 'users'), namespace='users')),
    path('products/', include(('apps.products.urls', 'products'), namespace='products')),
    path('orders/', include(('apps.orders.urls', 'orders'), namespace='orders')),
    path('notifications/', include(('apps.notifications.urls', 'notifications'), namespace='notifications')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from datetime import date

from datetime import date
from dateutil.relativedelta import relativedelta

from apps.users.models import Profile, ProfileAddress, ProfilePayment, ShoppingCart
class SignUpForm(forms.Form):

    username = forms.CharField(
        min_length=4,
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    password = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    password_confirmation = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    first_name = forms.CharField(
        min_length=2,
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    last_name = forms.CharField(
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )

    def clean_username(self):
        """username must be unique"""
        username = self.cleaned_data['username']
        username_exists = User.objects.filter(username=username).exists()

        if username_exists:
            raise forms.ValidationError('Username already Taken')
        return username

    def clean(self):
        """verifies password confirmation"""
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match')

        return data

    def save(self):
        """create user in database"""
        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()
        cart = ShoppingCart.objects.create(profile=profile)

class ProfileAddressForm(forms.ModelForm):
    """Form definition for ProfileAddress."""

    class Meta:
        """Meta definition for ProfileAddressform."""

        model = ProfileAddress
        exclude = ('profile', )
        widgets = {
            'main_street': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Main Street'}
            ),
            'number': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Number'}
            ),
            'secondary_street': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Secondary Street'}
            ),
            'notes': forms.Textarea(
                attrs={'class': 'form-control', 'rows': 2, 'placeholder': 'References'}
            ),
            'zip_code': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'ZIP Code'}
            ),
            'city': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'City'}
            ),
            'state': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'State'}
            ),
            'country': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Country'}
            ),
            'type': forms.RadioSelect()
        }

class ProfilePaymentForm(forms.ModelForm):
    """Form definition for ProfilePayment."""

    class Meta:
        """Meta definition for ProfilePaymentform."""

        model = ProfilePayment
        fields = (
            'card_number',
            'card_expiration_month',
            'card_expiration_year',
        )
        widgets = {
            'card_number': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'XXXX XXXX XXXX XXXX'}
            ),
            'card_expiration_month': forms.Select(
                choices=[(i, i) for i in range(1, 13)],
                attrs={'class': 'form-control'}
            ),
            'card_expiration_year': forms.Select(
                choices=[(i, i) for i in range(date.today().year, date.today().year + 30)],
                attrs={'class': 'form-control'}
            ),
        }

    def clean(self):
        cleaned_data =  super().clean()

        month = cleaned_data['card_expiration_month']
        year = cleaned_data['card_expiration_year']
        # we ensure that the expration date is valid
        last_card_expiration_day = date(year, month, 1) + relativedelta(days=31)
        if date.today() > last_card_expiration_day:
            raise ValidationError(
                "Expiration date is outdated"
            )

        return cleaned_data

apps/users/views.py
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.views.generic import FormView, DetailView, ListView, CreateView, UpdateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin

from apps.users.forms import SignUpForm, ProfileAddressForm, ProfilePaymentForm
from apps.users.models import Profile, ProfileAddress, ProfilePayment, ShoppingCart, ShoppingCartLine
from apps.products.models import Product, ProductQuestion
from apps.orders.models import OrderLine
from apps.notifications.mixins import NotificationMixin
# Create your views here.
class SignUpView(FormView):
    """Users sign up view."""

    template_name = 'users/user/signup.html'
    form_class = SignUpForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """Save form data."""
        form.save()
        return super().form_valid(form)

class LoginView(auth_views.LoginView):
    """Login view."""

    template_name = 'users/user/login.html'

class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """Logout view."""

    template_name = 'users/user/logged_out.html'


class ProfileDetailView(LoginRequiredMixin, NotificationMixin, DetailView):
    model = Profile
    template_name = "users/user/profile.html"

    def get_object(self):
        return self.request.user.profile

class ProfileChangePasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name = "users/user/change_password.html"
    success_message = "Your password has been changed succesfully"
    success_url = reverse_lazy('users:my-profile')

    def get_object(self):
        return self.request.user.profile


class ProfileAddressListView(LoginRequiredMixin, NotificationMixin, ListView):
    model = ProfileAddress
    template_name = "users/address/list.html"
    context_object_name = 'addresses'

    def get_queryset(self):
        queryset = ProfileAddress.objects.filter(
            profile=self.request.user.profile
        )
        return queryset


class ProfileAddressCreateView(LoginRequiredMixin, NotificationMixin, CreateView):
    model = ProfileAddress
    template_name = "users/address/create.html"
    form_class = ProfileAddressForm
    success_url = reverse_lazy('users:address:list')

    def form_valid(self, form):
        form.instance.profile = self.request.user.profile
        return super().form_valid(form)

    def get_success_url(self):
        if self.request.GET.get('from_order',False):
            return reverse_lazy('orders:create')
        return super().get_success_url()

class ProfileAddressUpdateView(LoginRequiredMixin, NotificationMixin, UpdateView):
    model = ProfileAddress
    template_name = "users/address/edit.html"
    success_url = reverse_lazy('users:address:list')
    form_class = ProfileAddressForm

def delete_profile_address(request, pk):
    address = ProfileAddress.objects.get(pk=pk)
    address.delete()
    return redirect('users:address:list')

## PROFILE PAYMENT VIEWS
class ProfilePaymentListView(LoginRequiredMixin, NotificationMixin, ListView):
    model = ProfilePayment
    template_name = "users/payments/list.html"
    context_object_name = 'payment_cards'

    def get_queryset(self):
        queryset = self.model.objects.filter(
            profile=self.request.user.profile
        )
        return queryset

class ProfilePaymentCreateView(LoginRequiredMixin, NotificationMixin, CreateView):
    model = ProfilePayment
    template_name = "users/payments/create.html"
    form_class = ProfilePaymentForm
    success_url = reverse_lazy('users:paymentcard:list')

    def form_valid(self, form):
        card_provider = {
            '3': 'American Express',
            '4': 'Visa',
            '5': 'Mastercard'
        }
        form.instance.profile = self.request.user.profile
        form.instance.card_provider = card_provider.get(
            form.instance.card_number[0], 'Other'
        )
        return super().form_valid(form)

    def get_success_url(self):
        if self.request.GET.get('from_order',False):
            return reverse_lazy('orders:create')
        return super().get_success_url()

class ProfilePaymentUpdateView(LoginRequiredMixin, NotificationMixin, UpdateView):
    model = ProfilePayment
    template_name = "users/payments/edit.html"
    success_url = reverse_lazy('users:paymentcard:list')
    form_class = ProfilePaymentForm

def delete_profile_payment(request, pk):
    address = ProfilePayment.objects.get(pk=pk)
    address.delete()
    return redirect('users:paymentcard:list')

class PublishedProductsListView(LoginRequiredMixin, NotificationMixin, ListView):
    model = Product
    template_name = "users/published_products/list.html"
    context_object_name = 'published_products'

    def get_queryset(self):
        return Product.objects.filter(
            seller=self.request.user.profile
        )

class ShoppingCartView(LoginRequiredMixin, NotificationMixin, DetailView):
    model = ShoppingCart
    template_name = 'users/cart.html'
    context_object_name = 'cart'

    def get_object(self):
        return self.request.user.profile.shopping_cart

@login_required
def change_product_qty(request, pk):
    type = request.GET['type']
    line = get_object_or_404(ShoppingCartLine, pk=pk)
    if type == 'add':
        line.quantity += 1
    if type == 'subtract' and line.quantity > 0:
        line.quantity -= 1
    line.save()
    return redirect('users:cart:cart')

@login_required
def remove_item(request, pk):
    line = get_object_or_404(ShoppingCartLine, pk=pk)
    line.delete()
    return redirect('users:cart:cart')


class ProductQuestionListView(LoginRequiredMixin, NotificationMixin, ListView):
    model = ProductQuestion
    template_name = "products/questions/unanswered_questions.html"
    context_object_name = 'unanswered_questions'

    def get_queryset(self):
        return ProductQuestion.objects.filter(
            responder=self.request.user.profile,
            answer=''
        )

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['answered_questions'] = ProductQuestion.objects.filter(
            responder=self.request.user.profile,
        ).exclude(answer='')
        return context

@login_required
def update_stock_qty(request, pk):
    if request.method == 'POST' and request.POST.get('new_stock_qty'):
        new_stock_qty = int(request.POST.get('new_stock_qty'))
        if new_stock_qty >= 0:
            product = get_object_or_404(
                Product,
                pk=pk,
                seller=request.user.profile
            )
            product.stock_qty = new_stock_qty
            product.save()
    return redirect('users:published-products')

templates/users/user/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
        crossorigin="anonymous">
    <link rel="stylesheet"
        href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"
        crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body class="h-100">

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">
                {% block container %}{% endblock%}
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>

</body>
</html>

templates/users/user/change_password.html
{% extends 'base.html' %}


{% block head_content %}
    <title>Change Password</title>
{% endblock head_content %}


{% block container %}
    <div class="card">
        <div class="card-header">
            <h5>Change Password</h5>
        </div>
        <div class="card-body">

            <form action="{% url 'users:change-password' %}" method="post">{% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary" type="submit">Submit</button>
            </form>
        </div>
    </div>
{% endblock container %}

templates/users/user/login.html
{% extends 'users/user/base.html' %}

{% block head_content %}
<title>D - COMMERCE | Sign In</title>
{% endblock %}

{% block container %}
    <div class="container mt-5 w-75 border rounded text-center">
        <h1>Sign In</h1>

        {% if form.errors %}
            <p class="alert alert-danger"> Invalid Username or Password. Please Try Again</p>
        {% endif %}

        <form action="{% url 'users:login' %}" method="post">{% csrf_token %}
            <div class="form-group">
                <input class="form-control" type="text" placeholder="Username" name="username" value="{{retry_username}}">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" placeholder="Password" name="password">
            </div>
            <br>
            <button class="btn btn-primary w-100" type="submit">Sign in</button>
        </form>
        <p class="mt-4">Don't have an account yet? <a href="{% url 'users:signup' %}">Sign Up Here</a></p>
    </div>
{% endblock %}

templates/users/user/profile.html
{% extends 'base.html' %}


{% block head_content %}
    <title>My Profile</title>
{% endblock head_content %}


{% block container %}
<div class="row">

    {# Attributes #}
    <div class="col-3 me-2">

        <h4>Sales</h4>
        <ul class="list-group">
            <a class="list-group-item" href="{% url 'users:published-products' %}">Published Products</a>
            <a class="list-group-item" href="{% url 'users:questions' %}">Questions</a>
            <a class="list-group-item" href="{% url 'orders:sales-list' %}">Sales</a>
        </ul>

        <br>

        <h4>Purchases</h4>
        <ul class="list-group">
            <a class="list-group-item" href="{% url 'orders:list' %}">My Orders</a>
        </ul>

        <br>

        <h4>Settings</h4>
        <ul class="list-group">
            <a class="list-group-item" href="{% url 'users:change-password' %}">Change Password</a>
            <a class="list-group-item" href="{% url 'users:address:list' %}">Addresses</a>
            <a class="list-group-item" href="{% url 'users:paymentcard:list' %}">Payment Cards</a>
        </ul>

    </div>

    {# Dashboard #}
    <div class="col-8 border rounded">
        <h1 class="mt-3">Notifications</h1>
        <hr>
        <ul class="list-group list-group-flush">

            {% for notif in profile.received_notifications.all %}
            <a href="{% url 'notifications:as_read' notif.pk%}" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5>
                        {% if not notif.is_read %}
                            <span class="badge rounded-pill bg-primary">New</span>
                        {% endif %}
                        {{notif.title}}
                    </h5>
                    <small class="text-muted">{{notif.created_at}}</small>
                </div>
                <small>{{notif.message}}</small>
            </a>
            {% empty %}
            <li class="list-group-item">
                <h2>There are no notifications</h2>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock container %}

templates/users/user/signup.html
{% extends 'users/user/base.html' %}

{% block head_content %}
<title>Sign Up</title>
{% endblock %}

{% block container %}

    <h1 style="text-align: center;">Sign Up</h1>

    {% if error %}
        <p class="alert alert-danger">{{error}}</p>
    {% endif %}

    <form action="{% url 'users:signup' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary btn-block mt-5" type="submit">Register</button>
    </form>

{% endblock %}